# Generated by Django 3.0.3 on 2020-06-16 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='description',
            field=models.CharField(default='Tets', max_length=300),
            preserve_default=False,
        ),
    ]
